# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33fdd6e2ff857b9d9fa22850eb5966e7279bc3f711740cdcc0deec2e08eb7a26c1d8e89e3a2f45a2c8fde53bf01fa48fe35ba7d9f7be42da853df49de72d3097

test:
  secret_key_base: 1956fb156fe62a58beccbfaa7d8bf89bfee3acd6b659e6cfa6de27adaad0cbd8f8363e68531745c4ed7a7c4be5096c8015cde0827bb0c43fa300a90c118364db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
